document.writeln("<div id=\"bookmark_part\">");
document.writeln("    <link rel=\"stylesheet\" href=\"icon/svg.css\">");
document.writeln("    <div id=\"box_container\">");
document.writeln("");
document.writeln("        <div class=\"box\">");
document.writeln("            <p class=\"title\" aria-hidden=\"true\"></p>");
document.writeln("            <div class=\"overlay\" style=\"background: url(\'icon/sparkk/star.svg\') no-repeat;background-size: 80%;background-position:center center;\"></div>");
document.writeln("            <p class=\"url\" aria-hidden=\"true\">书签</p>");
document.writeln("            <a href=\"folder://\" onclick=\"\" title=\"书签\"></a>");
document.writeln("        </div>");
document.writeln("        ");
document.writeln("        <div class=\"box\">");
document.writeln("            <p class=\"title\" aria-hidden=\"true\"></p>");
document.writeln("            <div class=\"overlay\" style=\"background: url(\'icon/sparkk/align-left.svg\') no-repeat;background-size: 80%;background-position:center center;\"></div>");
document.writeln("            <p class=\"url\" aria-hidden=\"true\">历史</p>");
document.writeln("            <a href=\"history://\" onclick=\"\" title=\"历史\"></a>");
document.writeln("        </div>");
document.writeln("");
document.writeln("        <div class=\"box\">");
document.writeln("            <p class=\"title\" aria-hidden=\"true\"></p>");
document.writeln("            <div class=\"overlay\" style=\"background: url(\'icon/sparkk/grid.svg\') no-repeat;background-size: 80%;background-position:center center;\"></div>");
document.writeln("            <p class=\"url\" aria-hidden=\"true\">Infinity</p>");
document.writeln("            <a href=\"https://m.inftab.com/#/\" title=\"Infinity\"></a>");
document.writeln("        </div>");
document.writeln("");
document.writeln("        <div class=\"box\">");
document.writeln("            <p class=\"title\" aria-hidden=\"true\"></p>");
document.writeln("            <div class=\"overlay\" style=\"background: url(\'icon/sparkk/menu.svg\') no-repeat;background-size: 80%;background-position:center center;\"></div>");
document.writeln("            <p class=\"url\" aria-hidden=\"true\">via</p>");
document.writeln("            <a href=\"\" onclick=\"window.via.cmd(514)\" title=\"搜索\"></a>");
document.writeln("        </div>");
document.writeln("");
document.writeln("        <div style=\"text-align: center;margin-bottom:20px;\">");
document.writeln("            <font color=\"#757575\" size=\"5px\">―·❀·―</font>");
document.writeln("        </div>");
document.writeln("");
document.writeln("    </div>");
document.writeln("</div>");
