document.writeln("<div id=\"bookmark_part\">");
document.writeln("    <link rel=\"stylesheet\" href=\"icon/svg.css\">");
document.writeln("    <div id=\"box_container\">");
document.writeln("");
document.writeln("        <div class=\"box\">");
document.writeln("            <p class=\"title\" aria-hidden=\"true\"></p>");
document.writeln("            <div class=\"overlay\" style=\"background: url(\'icon/sparkk/star.svg\') no-repeat;background-size: 80%;background-position:center center;\"></div>");
document.writeln("            <p class=\"url\" aria-hidden=\"true\">");
document.writeln("                书签");
document.writeln("            </p>");
document.writeln("            <a href=\"folder://\" onclick=\"\" title=\"书签\"></a>");
document.writeln("        </div>");
document.writeln("");
document.writeln("        <div class=\"box\">");
document.writeln("            <p class=\"title\" aria-hidden=\"true\"></p>");
document.writeln("            <div class=\"overlay\" style=\"background: url(\'icon/sparkk/align-left.svg\') no-repeat;background-size: 80%;background-position:center center;\"></div>");
document.writeln("            <p class=\"url\" aria-hidden=\"true\">");
document.writeln("                历史");
document.writeln("            </p>");
document.writeln("            <a href=\"history://\" onclick=\"\" title=\"历史\"></a>");
document.writeln("        </div>");
document.writeln("");
document.writeln("        <div class=\"box\">");
document.writeln("            <p class=\"title\" aria-hidden=\"true\"></p>");
document.writeln("            <div class=\"overlay\" style=\"background: url(\'icon/sparkk/grid.svg\') no-repeat;background-size: 80%;background-position:center center;\"></div>");
document.writeln("            <p class=\"url\" aria-hidden=\"true\">");
document.writeln("                Infinity");
document.writeln("            </p>");
document.writeln("            <a href=\"https://m.inftab.com/#/\" title=\"Infinity\"></a>");
document.writeln("        </div>");
document.writeln("");
document.writeln("        <div class=\"box\">");
document.writeln("            <p class=\"title\" aria-hidden=\"true\">");
document.writeln("                N");
document.writeln("            </p>");
document.writeln("            <div class=\"overlay\" style=\"background: url(\'icon/sparkk/menu.svg\') no-repeat;background-size: 80%;background-position:center center;\"></div>");
document.writeln("            <p class=\"url\" aria-hidden=\"true\">");
document.writeln("                导航");
document.writeln("            </p>");
document.writeln("            <a href=\"\" onclick=\"window.via.cmd(514)\" title=\"导航\"></a>");
document.writeln("            <select name=\"\" onchange=\"javascript:location.href=this.value;\">");
document.writeln("                <option value=\"http://www.zol.com.cn\" selected=\"selected\">zol</option>");
document.writeln("                <option value=\"http://www.163.com\">163</option>");
document.writeln("                <option value=\"http://www.sina.com\">sina</option>");
document.writeln("                <option value=\"http://www.sohu.com\">sohu</option>");
document.writeln("            </select>");
document.writeln("        </div>");
document.writeln("");
document.writeln("        <div style=\"text-align: center;margin-bottom:20px;\">");
document.writeln("            <font color=\"#757575\" size=\"5px\">―·❀·―</font>");
document.writeln("        </div>");
document.writeln("");
document.writeln("    </div>");
document.writeln("</div>");
